#!/bin/sh

xsetroot -cursor_name left_ptr

export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_CURRENT_DESKTOP=BSPWM
export BROWSER=firefox

dbus-update-activation-environment --all

# Monitor / desktop layout
bspc monitor -d I II III IV V VI VII VIII IX X

# Tiling / layout behavior
bspc config split_ratio        0.52
bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config single_monocle     true

# Border and gap sizes
bspc config border_width  2
bspc config window_gap    6

# Mouse / focus behavior
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config pointer_follows_monitor true
# bspc config ignore_ewmh_focus     true

# Everforest
bspc config normal_border_color   "#4c555b"
bspc config active_border_color   "#7a8478"
bspc config focused_border_color  "#a7c080"
bspc config presel_feedback_color "#83c092"

~/.config/bspwm/scripts.d/startup.sh &

