#!/bin/bash
distro=$(/usr/bin/awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"')
host=$(/usr/bin/hostname)
wm=$(/usr/bin/wmctrl -m | /usr/bin/awk '/Name:/ {print $2}')
packages=$(/usr/bin/pacman -Qq | wc -l)
kernel=$(/usr/bin/uname -r)
uptime=$(/usr/bin/uptime -p | /usr/bin/grep -ohe 'up .*' | /usr/bin/sed 's/up //')
GPU=$(lspci | grep -i vga | awk '/NVIDIA/ { for (i=8; i<=NF; i++) printf "%s ", $i; printf "\n" }' | sed -e 's/\[//' -e 's/\/.*//')
CPU=$(lscpu | grep "Modem ismi" | sed -e 's/Modem ismi://' -e 's/^ *//')
total_memory=$(/usr/bin/free -m | /usr/bin/awk '/Mem/ {print $2}')
used_memory=$(/usr/bin/free -m | /usr/bin/awk '/Mem/ {print $3}')

RED="\033[1;31m"
GREEN="\033[1;32m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
MAGENTA="\033[1;35m"
CYAN="\033[1;36m"
WHITE="\033[1;37m"
NC='\033[0m'

ascii_art="
${WHITE}                     .${NC}
${WHITE}                    / V\\ ${NC}
${WHITE}                  / \`  /${NC}     ${YELLOW}os${NC}     ${WHITE}${distro}${NC}
${WHITE}                 <<   |${NC}      ${YELLOW}host${NC}   ${WHITE}${host}${NC}
${WHITE}                 /    |${NC}      ${YELLOW}wm${NC}     ${WHITE}${wm}${NC}
${WHITE}               /      |${NC}      ${YELLOW}kernel${NC} ${WHITE}${kernel}${NC}
${WHITE}             /        |${NC}      ${YELLOW}uptime${NC} ${WHITE}${uptime}${NC}
${WHITE}           /    \\  \\ /${NC}       ${YELLOW}pkgs${NC}   ${WHITE}${packages}${NC}
${WHITE}          (      ) | |${NC}       ${YELLOW}GPU${NC}    ${WHITE}${CPU}${NC}
${WHITE}  ________|   _/_  | |${NC}       ${YELLOW}GPU${NC}    ${WHITE}${GPU}${NC}
${WHITE}<__________\\______)\__)${NC}      ${YELLOW}memory${NC} ${WHITE}${total_memory}MiB - ${used_memory}MiB${NC}"    

/usr/bin/echo -e "$ascii_art"