#!/bin/sh

distro=$(/usr/bin/awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"')
host=$(/usr/bin/hostname)
wm=$(/usr/bin/wmctrl -m | /usr/bin/awk '/Name:/ {print $2}')
packages=$(/usr/bin/pacman -Qq | wc -l)
kernel=$(/usr/bin/uname -r)
uptime=$(/usr/bin/uptime -p)
memory=$(/usr/bin/free -m | /usr/bin/awk '/Mem/ {print $2 "M"}')

ascii_art="
                     .
                    / V\\
                  / \`  /     os     ${distro}
                 <<   |      host   ${host}
                 /    |      wm     ${wm}
               /      |      kernel ${kernel}
             /        |      uptime ${uptime}
           /    \\  \\ /       pkgs   ${packages}
          (      ) | |       memory ${memory}
  ________|   _/_  | |
<__________\\______)\__)"

/usr/bin/printf "%s \n" "$ascii_art"